/**
 * CDSE Overlay Updater — manages overlay lifecycle after operations.
 *
 * After every domain operation that changes the Snapshot:
 * 1. Current overlay is invalidated (model changed)
 * 2. If auto-refresh is enabled, request fresh overlay from backend
 * 3. Apply new overlay to SLD symbols
 *
 * INVARIANTS:
 * - Overlay NEVER modifies geometry
 * - Overlay based ONLY on Snapshot (not local state)
 * - No physics calculations in frontend
 * - Deterministic: same Snapshot → same overlay
 */

import type { OverlayPayloadV1 } from '../../../ui/sld-overlay/overlayTypes';

/**
 * Overlay state managed by the updater.
 */
export interface OverlayState {
  /** Current active overlay payload (null = no overlay) */
  payload: OverlayPayloadV1 | null;
  /** Whether overlay is enabled (visible) */
  enabled: boolean;
  /** Whether overlay is stale (model changed since last load) */
  isStale: boolean;
  /** Whether auto-refresh is enabled */
  autoRefresh: boolean;
  /** Last run_id that produced this overlay */
  lastRunId: string | null;
}

/**
 * Create initial overlay state (no overlay active).
 */
export function createInitialOverlayState(): OverlayState {
  return {
    payload: null,
    enabled: false,
    isStale: false,
    autoRefresh: true,
    lastRunId: null,
  };
}

/**
 * Invalidate current overlay after a model change.
 *
 * Called after every domain operation that generates a new Snapshot.
 * If auto-refresh is enabled, the caller should then fetch a fresh overlay.
 *
 * @param state - Current overlay state
 * @returns Updated state with isStale = true
 */
export function invalidateOverlay(state: OverlayState): OverlayState {
  if (!state.payload) return state; // Nothing to invalidate
  return {
    ...state,
    isStale: true,
  };
}

/**
 * Apply a fresh overlay payload from backend.
 *
 * @param state - Current overlay state
 * @param payload - New overlay payload from backend analysis
 * @returns Updated state with fresh overlay
 */
export function applyOverlay(
  state: OverlayState,
  payload: OverlayPayloadV1,
): OverlayState {
  return {
    ...state,
    payload,
    enabled: true,
    isStale: false,
    lastRunId: payload.run_id,
  };
}

/**
 * Clear overlay (disable completely).
 */
export function clearOverlay(state: OverlayState): OverlayState {
  return {
    ...state,
    payload: null,
    enabled: false,
    isStale: false,
    lastRunId: null,
  };
}

/**
 * Toggle overlay visibility.
 */
export function toggleOverlay(state: OverlayState): OverlayState {
  return {
    ...state,
    enabled: !state.enabled,
  };
}

/**
 * Check if overlay needs refresh (stale + auto-refresh enabled).
 */
export function needsRefresh(state: OverlayState): boolean {
  return state.isStale && state.autoRefresh && state.payload !== null;
}

/**
 * Overlay consequence preview — lightweight summary after an operation.
 *
 * Shows immediate impact without full analysis run:
 * - Elements with changed loading
 * - Elements with new warnings
 * - Elements approaching limits
 *
 * All data comes from DomainOpResponse, NOT computed locally.
 */
export interface OverlayConsequencePreview {
  /** Elements whose loading changed */
  loadingChanges: Array<{
    elementId: string;
    label_pl: string;
    loading_before_pct: number | null;
    loading_after_pct: number | null;
  }>;
  /** New warnings generated by the operation */
  newWarnings: Array<{
    elementId: string;
    warning_pl: string;
  }>;
  /** Whether the model state changed enough to warrant re-analysis */
  requiresReanalysis: boolean;
}

/**
 * Create empty consequence preview.
 */
export function emptyConsequencePreview(): OverlayConsequencePreview {
  return {
    loadingChanges: [],
    newWarnings: [],
    requiresReanalysis: false,
  };
}
