import type { InspectorView } from './types';

export const sampleProofData: InspectorView = {
  document_id: '550e8400-e29b-41d4-a716-446655440000',
  artifact_id: '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
  created_at: '2026-01-27T10:29:55Z',
  proof_type: 'SC3F_IEC60909',
  title: 'Dowód zwarcia trójfazowego IEC 60909',
  header: {
    analysis_label: 'Zwarcie trójfazowe IEC 60909',
    standard_ref: 'IEC 60909-0:2016',
    project_name: 'Projekt SN-01',
    case_name: 'Zwarcie na szynie B2',
    run_timestamp: '2026-01-27T10:29:55Z',
    solver_version: '1.2.0',
    run_id: 'run-550e8400',
    snapshot_id: 'snapshot-6ba7b810',
    fingerprint: 'sha256:abc123def456',
    fault_location: 'Szyna B2',
    fault_type: 'SC3F',
    voltage_factor: 1.1,
    source_bus: 'B1',
    target_bus: 'B2',
  },
  steps: [
    {
      step_number: 1,
      step_id: 'SC3F_STEP_001',
      title: 'Napięcie z współczynnikiem c',
      equation_id: 'EQ_SC3F_001',
      formula_latex: '$$U = c \\cdot U_n$$',
      standard_ref: 'IEC 60909-0:2016',
      input_values: [
        {
          symbol: 'c',
          value: '1.100',
          unit: '—',
          mapping_key: 'c_factor',
          raw_value: 1.1,
        },
        {
          symbol: 'U_n',
          value: '15.00',
          unit: 'kV',
          mapping_key: 'u_n_kv',
          raw_value: 15,
        },
      ],
      substitution_latex: '$$U = 1.100 \\cdot 15.00 = 16.50\\,\\text{kV}$$',
      result: {
        symbol: 'U',
        value: '16.50',
        unit: 'kV',
        mapping_key: 'u_prefault_kv',
        raw_value: 16.5,
      },
      unit_check: {
        passed: true,
        derivation: '—',
        expected_unit: 'kV',
        computed_unit: 'kV',
      },
    },
    {
      step_number: 2,
      step_id: 'VDROP_STEP_001',
      title: 'Rezystancja odcinka',
      equation_id: 'EQ_VDROP_001',
      formula_latex: '$$R = r \\cdot l$$',
      standard_ref: 'IEC 60909-0:2016',
      input_values: [
        {
          symbol: 'r',
          value: '0.120',
          unit: 'Ω/km',
          mapping_key: 'r_ohm_per_km',
          raw_value: 0.12,
        },
        {
          symbol: 'l',
          value: '2.00',
          unit: 'km',
          mapping_key: 'length_km',
          raw_value: 2,
        },
      ],
      substitution_latex: '$$R = 0.120 \\cdot 2.00 = 0.240\\,\\Omega$$',
      result: {
        symbol: 'R',
        value: '0.240',
        unit: 'Ω',
        mapping_key: 'r_ohm',
        raw_value: 0.24,
      },
      unit_check: {
        passed: true,
        derivation: 'Ω/km · km = Ω',
        expected_unit: 'Ω',
        computed_unit: 'Ω',
      },
    },
    {
      step_number: 3,
      step_id: 'QU_STEP_001',
      title: 'Wartość Q zadana',
      equation_id: 'EQ_QU_001',
      formula_latex: '$$Q_{cmd} = Q_{raw}$$',
      standard_ref: 'IEC 60909-0:2016',
      input_values: [
        {
          symbol: 'Q_{raw}',
          value: '2.50',
          unit: 'Mvar',
          mapping_key: 'q_raw_mvar',
          raw_value: 2.5,
        },
      ],
      substitution_latex: '$$Q_{cmd} = 2.50\\,\\text{Mvar}$$',
      result: {
        symbol: 'Q_{cmd}',
        value: '2.50',
        unit: 'Mvar',
        mapping_key: 'q_cmd_mvar',
        raw_value: 2.5,
      },
      unit_check: {
        passed: true,
        derivation: 'Mvar = Mvar',
        expected_unit: 'Mvar',
        computed_unit: 'Mvar',
      },
    },
    {
      step_number: 4,
      step_id: 'SC1_STEP_001',
      title: 'Impedancja zastępcza',
      equation_id: 'EQ_SC1_001',
      formula_latex: '$$Z_k = Z_1 + Z_2 + Z_0$$',
      standard_ref: 'IEC 60909-0:2016',
      input_values: [
        {
          symbol: 'Z_1',
          value: '0.50 + j1.20',
          unit: 'Ω',
          mapping_key: 'z1_ohm',
          raw_value: '0.5+j1.2',
        },
        {
          symbol: 'Z_2',
          value: '0.50 + j1.20',
          unit: 'Ω',
          mapping_key: 'z2_ohm',
          raw_value: '0.5+j1.2',
        },
        {
          symbol: 'Z_0',
          value: '1.10 + j2.20',
          unit: 'Ω',
          mapping_key: 'z0_ohm',
          raw_value: '1.1+j2.2',
        },
      ],
      substitution_latex:
        '$$Z_k = (0.50 + j1.20) + (0.50 + j1.20) + (1.10 + j2.20)$$',
      result: {
        symbol: 'Z_k',
        value: '2.10 + j4.60',
        unit: 'Ω',
        mapping_key: 'z_equiv_ohm',
        raw_value: '2.1+j4.6',
      },
      unit_check: {
        passed: false,
        derivation: 'Ω + Ω + Ω = Ω',
        expected_unit: 'Ω',
        computed_unit: 'Ω',
      },
    },
  ],
  summary: {
    key_results: {
      ikss_ka: {
        symbol: "I_k''",
        value: '4.62',
        unit: 'kA',
        mapping_key: 'ikss_ka',
        raw_value: 4.62,
      },
      u_prefault_kv: {
        symbol: 'U',
        value: '16.50',
        unit: 'kV',
        mapping_key: 'u_prefault_kv',
        raw_value: 16.5,
      },
    },
    unit_check_passed: false,
    total_steps: 4,
    warnings: ['Wykryto brak zgodności jednostek w kroku SC1.'],
  },
  counterfactual: {
    rows: [
      {
        name: 'Q_cmd',
        symbol_latex: 'Q_{cmd}',
        unit: 'Mvar',
        value_a: 1.8,
        value_b: 2.5,
        delta: 0.7,
        step_id: 'QU_STEP_001',
      },
      {
        name: 'U',
        symbol_latex: 'U',
        unit: 'kV',
        value_a: 15.9,
        value_b: 16.5,
        delta: 0.6,
        step_id: 'SC3F_STEP_001',
      },
    ],
    has_vdrop_data: true,
  },
  is_counterfactual: true,
  export_availability: {
    json: true,
    latex: true,
    pdf: false,
  },
  export_payloads: {
    json: '{"proof_type":"SC3F_IEC60909"}',
    latex: '% LaTeX export placeholder',
  },
};
