"""
Katalog zasilan systemowych SN (GPZ / warunki zasilania OSD).

Pozycje reprezentuja jawne, audytowalne kontrakty techniczne dla zrodla GPZ.
Brak domyslowania: parametry zwarciowe i napieciowe pochodza z katalogu.
"""

from __future__ import annotations

from typing import Any


SOURCE_SYSTEM_TYPES: list[dict[str, Any]] = [
    {
        "id": "src-gpz-15kv-200mva-rx010",
        "name": "Zasilanie GPZ 15 kV / Sk3 200 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 15.0,
            "sk3_mva": 200.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-15-200-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-15kv-250mva-rx010",
        "name": "Zasilanie GPZ 15 kV / Sk3 250 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 15.0,
            "sk3_mva": 250.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-15-250-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-15kv-300mva-rx010",
        "name": "Zasilanie GPZ 15 kV / Sk3 300 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 15.0,
            "sk3_mva": 300.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-15-300-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-15kv-350mva-rx010",
        "name": "Zasilanie GPZ 15 kV / Sk3 350 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 15.0,
            "sk3_mva": 350.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-15-350-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-15kv-400mva-rx010",
        "name": "Zasilanie GPZ 15 kV / Sk3 400 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 15.0,
            "sk3_mva": 400.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-15-400-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-15kv-500mva-rx010",
        "name": "Zasilanie GPZ 15 kV / Sk3 500 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 15.0,
            "sk3_mva": 500.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-15-500-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-15kv-500mva-rx012",
        "name": "Zasilanie GPZ 15 kV / Sk3 500 MVA / R/X 0.12",
        "params": {
            "voltage_rating_kv": 15.0,
            "sk3_mva": 500.0,
            "ik3_ka": None,
            "rx_ratio": 0.12,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-15-500-012",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-20kv-200mva-rx010",
        "name": "Zasilanie GPZ 20 kV / Sk3 200 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 20.0,
            "sk3_mva": 200.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-20-200-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-20kv-250mva-rx010",
        "name": "Zasilanie GPZ 20 kV / Sk3 250 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 20.0,
            "sk3_mva": 250.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-20-250-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-20kv-300mva-rx010",
        "name": "Zasilanie GPZ 20 kV / Sk3 300 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 20.0,
            "sk3_mva": 300.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-20-300-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-20kv-350mva-rx012",
        "name": "Zasilanie GPZ 20 kV / Sk3 350 MVA / R/X 0.12",
        "params": {
            "voltage_rating_kv": 20.0,
            "sk3_mva": 350.0,
            "ik3_ka": None,
            "rx_ratio": 0.12,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-20-350-012",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-20kv-400mva-rx012",
        "name": "Zasilanie GPZ 20 kV / Sk3 400 MVA / R/X 0.12",
        "params": {
            "voltage_rating_kv": 20.0,
            "sk3_mva": 400.0,
            "ik3_ka": None,
            "rx_ratio": 0.12,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-20-400-012",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-20kv-500mva-rx010",
        "name": "Zasilanie GPZ 20 kV / Sk3 500 MVA / R/X 0.10",
        "params": {
            "voltage_rating_kv": 20.0,
            "sk3_mva": 500.0,
            "ik3_ka": None,
            "rx_ratio": 0.10,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-20-500-010",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
    {
        "id": "src-gpz-20kv-500mva-rx012",
        "name": "Zasilanie GPZ 20 kV / Sk3 500 MVA / R/X 0.12",
        "params": {
            "voltage_rating_kv": 20.0,
            "sk3_mva": 500.0,
            "ik3_ka": None,
            "rx_ratio": 0.12,
            "earthing_system": "PUNKT_NEUTRALNY_UZIEMIONY",
            "short_circuit_model": "short_circuit_power",
            "operator_name": "OSD",
            "supply_role": "ZASILANIE_SYSTEMOWE",
            "manufacturer": "OSD",
            "series": "Warunki zasilania GPZ",
            "catalog_number": "GPZ-20-500-012",
            "data_source": "Warunki przylaczenia / standard OSD",
        },
    },
]


def get_all_source_system_types() -> list[dict[str, Any]]:
    """Zwraca pelny typoszereg zasilan systemowych GPZ."""
    return list(SOURCE_SYSTEM_TYPES)
